{
  "hash": "8803f35f27c10ba616e6639b613bdf7e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Can ELO Predict the Outcome of Chess Games?\"\nauthor: \"Francisco Cardozo\"\ndate: 2022-12-01\ncategories: [\"Chess\", \"Trees\", \"Machine Learning\"]\ntags: [\"Chess\", \"Trees\", \"Machine Learning\"]\nformat:\n  html:\n    code-fold: true\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ChessOlympiad22)\nlibrary(rpart.plot)\nlibrary(tidymodels)\n```\n:::\n\n\n\n\n\nThe [ELO rating system](https://en.wikipedia.org/wiki/Elo_rating_system){target=\"_blank\"} is a method used to calculate the relative skill levels of chess players, based on their game results. A higher ELO rating indicates a higher perceived skill level.\n\nIn this document, the ELO difference between two players is used to evaluate the probability of one player winning the match.\n\nI will use the The [ChessOlympiad](https://github.com/focardozom/ChessOlympiad22){target=\"_blank\"} package. It contains two datasets: `players` and `results`. The `players` dataset contains the ELO ratings of all players participating in the 44th Chess Olympiad, which took place in Chennai, India, in 2022. The `results` dataset contains the results of all matches played in the tournament.\n\n\n### Distribution of ELO \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"players\")\n```\n:::\n\n\n\n\nFirst, let's visualize the ELO distribution of the players. \n\nIt is important to filter out players with an ELO rating of zero from the analysis, as these players have not yet been rated and do not have a known skill level. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplayers |>\n    filter(rtg != 0) |>\n    ggplot(aes(rtg)) +\n    geom_histogram(bins = 90, fill = \"gray90\", alpha = 0.85, color = \"gray95\") +\n    scale_x_continuous(breaks = seq(1000, 2900, 150)) +\n    theme_minimal() +\n    theme(\n        axis.text.y = element_blank(),\n        panel.grid = element_blank()\n    ) +\n    labs(\n        x = \"Elo Rating System (Higher values indicate greater player strength)\",\n        y = \"\",\n        title = \"Elo Rating System of players in Chess Olympiad, 2022. Chennai, India \",\n        caption = \"Magnus Carlsen has the highest Elo rating in the tournament: 2864\"\n    ) +\n    geom_text(\n        data = players %>%\n            filter(rtg > 2800),\n        aes(\n            x = 2550,\n            y = 4.5,\n            label = \"Magnus Carlsen\"\n        ),\n        size = 3,\n        color = \"black\"\n    ) +\n    geom_curve(\n        data = players %>% filter(rtg > 2800),\n        aes(\n            x = 2700,\n            y = 4.4, xend = 2864.8,\n            yend = 1\n        ),\n        arrow = arrow(length = unit(0.3, \"cm\")),\n        color = \"red\",\n        linewidth = 0.5,\n        curvature = -0.5\n    )\n```\n\n::: {.cell-output-display}\n![](chess-olympiad22_files/figure-html/plots-with-palyers-1.png){width=672}\n:::\n:::\n\n\n\n\nIt may be interesting to plot the ELO ratings of players by federation, as the Chess Olympiad is played by national teams. By examining the ELO ratings of players within each federation, we can get a sense of the overall strength of the teams participating in the event. This analysis could potentially provide insight into the results of the Chess Olympiad and help predict the outcomes of matches. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplayers |>\n    filter(rtg > 2600) |>\n    ggplot(aes(reorder(fed, rtg), rtg)) +\n    theme_minimal() +\n    geom_boxplot() +\n    coord_flip() +\n    theme(panel.grid = element_blank()) +\n    labs(x = \"\", y = \"ELO\")\n```\n\n::: {.cell-output-display}\n![](chess-olympiad22_files/figure-html/elo-by-federation-1.png){width=672}\n:::\n:::\n\n\n\n\nAccording to ELO ratings, the United States fielded the strongest team in the tournament.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"results\")\n```\n:::\n\n\n\n\n\n### Differences in ELO by round\n\nThe Chess Olympiad followed a Swiss-style tournament, meaning that players are paired with opponents with similar scores in each round. Specifically, in the first round, the highest-ranked player is matched against the median-ranked player, followed by the second-highest ranked player against the next below median, and so forth.\n\nA visual representation of the differences in ELO by round are presented in the following graph. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults |>\n    filter(\n        elo_difference >= -1000,\n        elo_difference <= 1000,\n        !is.na(elo_white), !is.na(elo_black), elo_white != 0, elo_black != 0\n    ) |>\n    ggplot(aes(as.numeric(elo_white), elo_difference,\n        fill = factor(result_white),\n        color = factor(result_white)\n    )) +\n    geom_point(\n        shape = 21, alpha = 0.85,\n        size = 3, stroke = 0.5\n    ) +\n    theme_minimal() +\n    scale_fill_manual(values = c(\"Lost\" = \"black\", \"Draw\" = \"gray50\", \"Won\" = \"white\")) +\n    scale_color_manual(values = c(\"Lost\" = \"black\", \"Draw\" = \"black\", \"Won\" = \"black\")) +\n    labs(\n        fill = \"Result\", color = \"Result\",\n        x = \"Player Elo\",\n        y = \"Elo difference\",\n        caption = \"Difference greater than zero indicates stronger player\n       44th Chess Olympiad. Chennai, 2022 Open\"\n    ) +\n    facet_wrap(~round)\n```\n\n::: {.cell-output-display}\n![](chess-olympiad22_files/figure-html/plot-data-diff-1.png){width=672}\n:::\n:::\n\n\n\n\n# Model the winning chances for players with the white pieces based on ELO difference \n\nNow, let's try to identify the optimal divisions in ELO rating differences that could potentially classify the outcomes of chess games. For this, I will be using the `tidymodels` package to estimate a Classification and Regression Trees (CART) model. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncart_spec <-\n    decision_tree() |>\n    set_engine(\"rpart\") |>\n    set_mode(\"classification\")\n```\n:::\n\n\n\n\nI will add two steps in the recipe. One to filter the data set by round, and the other to convert results in a factor variable.  I also will limit my analysis to players with more than 1600 in ELO. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresults <- results |>\n    filter(as.numeric(elo_white) > 1600) |>\n    filter(as.numeric(elo_black) > 1600)\n\nrecipe <- recipe(\n    result_white ~ elo_difference + round_number,\n    data = results\n) |>\n    step_filter(round_number == round)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrkfl <- workflow() |>\n    add_model(cart_spec) |>\n    add_recipe(recipe)\n```\n:::\n\n\n\n\nLet's estimate the model for the round 1. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround <- 1\n\ncart_fit <- wrkfl |>\n    fit(data = results) |>\n    extract_fit_parsnip()\n```\n:::\n\n\n\n\n### Draw an tree to understand the results\n\nFinally, I will create a tree showing the splits\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncart_fit <- repair_call(cart_fit, data = round)\n\ncart_tree_fit <- cart_fit$fit\n\nrpart.plot::rpart.plot(cart_tree_fit, roundint = FALSE)\n```\n\n::: {.cell-output-display}\n![](chess-olympiad22_files/figure-html/draw-tree-1.png){width=672}\n:::\n:::\n\n\n\n\nAccording to the model, a difference of 12 in the ELO is sufficient to accurately predict the winner in 95% of cases and the loser in 91% of cases.\n\n\n# Model the last round \n\nNow, let's apply the model to the final round, which featured matches between the most formidable opponents.\n\nI will add a the `tree_depth` parameter to my model. The depth of the tree refers to the number of levels the tree has.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncart_spec <-\n    decision_tree(tree_depth = 4) |>\n    set_engine(\"rpart\") |>\n    set_mode(\"classification\")\n\nwrkfl <- workflow() |>\n    add_model(cart_spec) |>\n    add_recipe(recipe)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nround <- 11\n\ncart_fit <- wrkfl |>\n    fit(data = results)\n\ncart_fit <- wrkfl |>\n    fit(data = results) |>\n    extract_fit_parsnip()\n\ncart_fit <- repair_call(cart_fit, data = round)\n\ncart_tree_fit <- cart_fit$fit\n\nrpart.plot::rpart.plot(cart_tree_fit, roundint = FALSE)\n```\n\n::: {.cell-output-display}\n![](chess-olympiad22_files/figure-html/last-round-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrpart.rules(cart_tree_fit, cover = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  ..y  Dra Los Won                                       cover\n Draw [.45 .30 .25] when elo_difference is -176 to  85     51%\n Draw [.55 .09 .36] when elo_difference >=         333      4%\n Draw [.69 .15 .15] when elo_difference is   95 to 115      4%\n Lost [.29 .61 .10] when elo_difference <  -176            20%\n  Won [.10 .30 .60] when elo_difference is   85 to  95      3%\n  Won [.17 .20 .63] when elo_difference is  115 to 333     18%\n```\n\n\n:::\n:::\n\n\n\n\nThe color-coding of the decision tree leaves suggests that differences in ELO ratings remain a critical factor, even in the final round of the chess tournament. It seems that the model is particularly adept at predicting outcomes when the ELO differences are substantial. For example, if you have more than 333 points in ELO, the model predicts 63% wining chances for you. However, if the ELO difference is less than 333 (but more than 115), the model predicts  55% of draw.\n\nWhen the ELO difference is less than 115, the model's predictions become more interesting. If a player has 176 points less than their opponent, the model is more likely to classify them as a loser (61%). However, if the ELO difference is less than 85 points, the player still has a good chance of winning the game. This could be seen as an indicator of the performance of some players with lower ELO ratings who are having a strong tournament. On the other hand, if the ELO difference is greater than 85 points, most of the chances are for a draw.\n\nThis serves as a quick demonstration of how the ChessOlympiad package can be utilized in predictive modeling.\n",
    "supporting": [
      "chess-olympiad22_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}