execute:
  freeze: auto

project:
  type: website

website:
  google-analytics: "G-GJFPX0CGRL"
  cookie-consent: true
  title: Francisco Cardozo
  site-url: https://focardozom.github.io/
  description: "Francisco Cardozo is a prevention scientist at the University of Miami working on AI for program implementation, machine learning, and open-source R tools."
  image: https://focardozom.github.io/img/yo.JPEG
  favicon: img/favicon.png
  open-graph: true
  twitter-card: true
  back-to-top-navigation: true
  page-navigation: true
  page-footer:
    left: "© 2026 Francisco Cardozo"
    border: false
    right:
      - icon: github
        aria-label: GitHub
        href: https://github.com/focardozom
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - posts.qmd
      - publications.qmd
      - packages.qmd
    tools:
      - icon: github
        aria-label: GitHub
        href: https://github.com/focardozom
      - icon: mortarboard-fill
        aria-label: Google Scholar
        href: https://scholar.google.com/citations?user=X5BtC3wAAAAJ
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/fcardozom/
      - icon: rss
        aria-label: RSS feed
        href: posts.xml

format:
  html:
    theme:
     - cosmo
     - styles.scss
    toc: true



