execute:
  freeze: auto

project:
  type: website

website:
  google-analytics: "G-GJFPX0CGRL"
  cookie-consent: true
  title: Francisco Cardozo
  site-url: https://focardozom.github.io/
  description: "Francisco's personal website"
  back-to-top-navigation: true
  page-navigation: true
  page-footer:
    left: "© 2026 Francisco Cardozo"
    border: false
    right:
      - icon: github
        href: https://github.com/focardozom
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - posts.qmd
      - publications.qmd
      - packages.qmd
    tools:
      - icon: github
        href: https://github.com/focardozom
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@focardozom@nerdculture.de
        rel: "me"
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/francisco-cardozo-757050264/

format:
  html:
    theme:
     - cosmo
     - styles.scss
    toc: true



