project:
  type: website

website:
  title: Francisco Cardozo
  back-to-top-navigation: true
  page-footer: 
    left: "© 2023 Francisco Cardozo" 
    border: false
    right: 
      - icon: github
        href: https://github.com/focardozom
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - posts.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/focardozom09?lang=en
      - icon: github
        href: https://github.com/focardozom
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@focardozom@nerdculture.de
        rel: "me"
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/francisco-cardozo-757050264/


format:
  html:
    theme:
     - cosmo
     - styles.scss
    toc: true



