---
title: "To Explain or to Predict"
author: Francisco Cardozo
date: 2024-01-27
categories: ["Explain", "Prevention", "Predict"]
tags: ["Explain", "Prevention", "Predict"]
---

There is a current debate regarding the appropriate circumstances to employ machine learning (ML) over traditional statistics for statistical modeling. Some traditionalists assert that ML often represents nothing more than a rebrand version of existing methods, occasionally rendering it unnecessary. Their primary criticism is that while ML can be advantageous in some circumstances, it frequently operates as a “black box”, offering limited transparency and scant insights into the underlying phenomena. On the other hand, ML advocates argue that traditional statistics often fail to grasp the intricate complexities of real-world data, positioning ML as the superior option. Both arguments, however, might be missing the essence of the issue. This debate is not merely about the characteristics of the tools used but more about the foundational objectives of scientific research.

Scientific research predominantly deals with questions to respond ‘why’ and ‘when’ something occurs. When scientists seek explanations, they are interested in the primary causes or influencers of observed events. Predictive endeavors, conversely, are inherently forward-looking, valuing future forecasts over causal understanding. While no single statistical method can directly answer causal questions, prediction can be approached using both traditional regression techniques and ML models. Thus, the real dilemma emerges in choosing methods for predictive situations, as tools for causal explanations are beyond mere statistical techniques.

When predictive modeling is chosen, machine learning often proves more advantageous than traditional statistical models. These advantages stem from distinct characteristics inherent in the construction of ML models. Primarily, this is because the construction of machine learning models is guided by out-of-sample metrics, tailored to maximize the model's ability to generalize to unseen data. In essence, machine learning models seek a balance between variance and bias. Conversely, traditional statistical methods focus on hypothesis testing to draw conclusions from models, often overlooking concerns such as overfitting. This oversight includes practices like using the same dataset for both training and testing, and a lack of emphasis on metrics such as the Akaike Information Criterion (AIC), Bayesian Information Criterion (BIC), or adjusted R², which are crucial for evaluating model complexity. It should be mentioned that this traditional approach is not inherently wrong, but it is not the most appropriate for predictive modeling. Instead, these methods are excellent tools for descriptive analysis and most research in public health is descriptive (unfortunately?).

While machine learning models offer advantages, they also present several challenges. They frequently require extensive computational resources and, in numerous cases, cannot offer insights about underlying phenomena. Such shortcomings can be significant limitations in various scientific contexts. In these scenarios, traditional statistics often emerge as the preferred approach, due to their ability to summarize data relationships more straightforwardly.

In prevention science, differentiating between prediction and explanation is crucial. However, this distinction is often overlooked, resulting in innovative missteps. In the absence of clear guidelines, practitioners may opt for inappropriate tools, leading to confusion between predictive outcomes and causal relationships. For example, when assessing interventions, programs are typically evaluated with a focus on their theoretical foundations and the program’s underlying mechanisms, necessitating explanatory modeling. Yet, in practice, the models often tend to be predictive (or descriptive), thereby overlooking the methods essential for explanatory analysis.

In summary, the distinction between explanation and prediction is not merely about the methods or algorithms employed but centers on the overarching purpose of the research. While both are fundamental to scientific research, their practical applications and tools, especially in prevention science, can differ significantly.

